"""Add subtopic_table

Revision ID: c220bad690d3
Revises: 2c89765a59e7
Create Date: 2025-02-21 05:16:07.466347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c220bad690d3'
down_revision = '2c89765a59e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddCourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='statusenum'), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('diffculty_level', sa.Enum('BEGINNER', 'MEDIUM', 'ADVANCED', name='difficultyenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CourseContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1200), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['AddCourse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('coursecontent')
    op.drop_table('addcourse')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addcourse',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('language_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.ENUM('ACTIVE', 'CLOSED'), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diffculty_level', mysql.ENUM('BEGINNER', 'MEDIUM', 'ADVANCED'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('coursecontent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1200), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['addcourse.id'], name='coursecontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('CourseContent')
    op.drop_table('AddCourse')
    # ### end Alembic commands ###
