"""Fix data types for status and difficulty_level

Revision ID: eabd7cac3fcd
Revises: 
Create Date: 2025-02-21 03:45:07.490581

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eabd7cac3fcd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AddCourse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language_name', sa.String(length=255), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('diffculty_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_name')
    )
    op.create_table('CourseContent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=1200), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['AddCourse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('addcourse', schema=None) as batch_op:
        batch_op.drop_index('topic_name')

    op.drop_table('addcourse')
    op.drop_table('coursecontent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coursecontent',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('project_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('description', mysql.VARCHAR(length=1200), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['addcourse.id'], name='coursecontent_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('addcourse',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('language_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('topic_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('diffculty_level', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('addcourse', schema=None) as batch_op:
        batch_op.create_index('topic_name', ['topic_name'], unique=True)

    op.drop_table('CourseContent')
    op.drop_table('AddCourse')
    # ### end Alembic commands ###
